# Generated by Django 4.2.6 on 2023-10-22 13:46

import Library__main.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the book.', max_length=100, validators=[Library__main.models.bookNameValidator], verbose_name='Book title')),
                ('description', models.TextField(blank=True, help_text='Enter the description of the book.', verbose_name='Book description')),
                ('author', models.CharField(help_text='Enter the author of the book.', max_length=100, validators=[Library__main.models.nameValidator], verbose_name='Book author')),
                ('year_published', models.IntegerField(help_text='Enter the year of publication of the book.', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)], verbose_name='Year of publication')),
                ('genre', models.CharField(choices=[('Classic', 'Classic'), ('Fantastic', 'Fantastic'), ('Detective', 'Detective'), ('Fairy tales', 'Fairy tales'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Science fiction', 'Science fiction'), ('Thriller', 'Thriller'), ('Other', 'Other')], default='Other', help_text='Select the genre of the book.', max_length=100, verbose_name='Book genre')),
                ('publisher', models.CharField(blank=True, help_text='Enter the name of the publisher.', max_length=100, verbose_name='Book publisher')),
                ('amount', models.IntegerField(default=5, help_text='Enter the amount of books.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount of books in the library')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text="Enter the User's phone number.", max_length=12, validators=[Library__main.models.phoneValidator], verbose_name='Phone number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
