# Generated by Django 4.2.6 on 2023-10-22 18:14

import Library__main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library__main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text="Enter the User's phone number", max_length=12, validators=[Library__main.models.phoneValidator], verbose_name='Phone number'),
        ),
    ]
