# Generated by Django 4.2.6 on 2023-10-23 11:22

import Library__main.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library__main', '0003_alter_book_options_bookinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.IntegerField(help_text='Enter the year of publication of the book.', validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2023)], verbose_name='Year of publication'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text="Enter user's phone, e.g.: +11111111111", max_length=12, validators=[Library__main.models.phoneValidator], verbose_name='Phone number'),
        ),
    ]
