# Generated by Django 4.2.6 on 2023-10-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library__main', '0005_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Book availability', max_length=1, verbose_name='Book status'),
        ),
    ]
